### PR TITLE
Put users in descending chronological order

### PR DESCRIPTION
**Pull request by siaw23-retired**
This way it's easier to see the new users, instead of having to skip pages to reach the new users that have joined.

### CODE REVIEW

**Comment by siaw23-retired** [comment]
I almost went to bed when I remembered my previous commit would clear the snapcode images of previous members. So the last commit fixes that...

**Comment by siaw23-retired** [comment]
@andrzejkrzywda please don't accept this PR just yet, my last commit is not working on heroku. we might need to use S3 but the application owner needs to make some configurations which I can't... :)

**Comment by siaw23-retired** [comment]
@andrzejkrzywda i rebased my PR to remove storing snapcodes on heroku. this PR is OK. I will implement storing SVGs in the db as suggested by @paneq. please close or accept this PR. 😊

**Comment by andrzejkrzywda** [comment]
Thanks for this PR!

It seems that it contains a number of small improvements and one major change which is the order, right?

I'm happy with the small improvements!

I'm not yet sure what's the best way of dealing with the problem which you mentioned - that it's easier to add new users, when the order is reversed. Maybe we can have some cookie-based tracking and show the new people from your last visit?

Anyway, as for now I'm not convinced about changing the order. I'd like the early adopters (including me and you) to be at the top as a way of promoting and thanking them.

My suggestion - let's remove the ordering change from here and accept all else. Also, let's create an issue for discussing what's the best way to show new users here - I agree it's important!

Thanks for your help here!

**Comment by siaw23-retired** [comment]
great. i reversed the order again. your idea about pioneers being on the first page is cool. i was just trying to think of making things "easier" for others. for example, after visiting the page after 2 weeks, i see newest users first and add them. but i reversed the order again in my latest commit to be like it was before. (i'll push when i get home).

as for a way of showing new users, i'll leave it for others to attend to it. in the meantime i'll store snapcodes in the db and finish writing tests. the newest issue about migrations has been fixed already, pushing later today.

**Pull request merged**
