### PR TITLE
Make codes index responsive

### PR DESCRIPTION
**Pull request by rusilko**
This makes snapcodes view responsive and mobile friendly.
On the mobile user should see one code per "screen". This should allow to screenshot easily and then use snapchat "add from snapcode" feature easily.

screen shot 2016-04-12 at 12 01 58

### CODE REVIEW

**Comment by andrzejkrzywda** [comment]
I've just removed that view from the app. All the symptoms were showing that they have banned us and no images were displayed today. Also, that is clearly part of their private API, so I believe they don't want anyone to use it. What do you think?

Overall, I like the idea of one page with all codes - it's very convienent.

Did you use Ghostcodes? they require uploading your own snapcode (probably due to the same limitations). Maybe we can go their way somehow?

**Comment by rusilko** [comment]
Yeah, that sucks... Seems like they didn't ban us completely, some images are displayed. I am hitting it from localhost and it's stops working for some time and then comes back up.
I would suggest, hitting the API just once when new user is created and saving the image (maybe 64base encoded?). And then feeding the codes list from our data.

Alternatively we can make an upload field in the form... but that's less convenient.

What do you think?

**Comment by paneq** [comment]
@rusilko I wanted to suggest the same solution, to cache the image on our side :)

**Comment by andrzejkrzywda** [comment]
caching the image solves the availability problem, but it's probably still against their rules. if we're fine with that (no opinion here) then it's worth trying

**Comment by rusilko** [comment]
Do we know what are the rules? I have no experience in APIs but If the API is private how come we can access it? And what is this site: https://feelinsonice-hrd.appspot.com?

**Comment by andrzejkrzywda** [comment]
if you run `curl -I "https://feelinsonice-hrd.appspot.com/web/deeplink/snapcode?username=pankowecki&type=SVG"`

you'll see:

```
HTTP/1.1 200 OK
X-Snapchat-Request-Id: 570cd27200ff0cda6b4792d7180001737e6665656c696e736f6e6963652d68726400016d6173746572313335303130000101f2
X-Snapchat-Notice: Snapchat Private APIs - Unauthorized use is prohibited.
Content-Type: image/svg+xml
Content-Length: 11993
Date: Tue, 12 Apr 2016 10:48:19 GMT
Server: Google Frontend
Alternate-Protocol: 443:quic
Alt-Svc: quic=":443"; ma=2592000; v="32,31,30,29,28,27,26,25"
```

**Comment by rusilko** [comment]
Ah, I see. IMO let's do this. I'll try to code it today/tomorrow.
Are you OK with that?

**Comment by siaw23-retired** [comment]
i fixed the snapcode unavailability issue here 205ca0f now when a user adds himself, his snapcode will be downloaded and stored on our server once... so all snapcode images should always be available now.

**Comment by rusilko** [comment]
@siaw23 Will this work on heroku? I mean saving files?

On a separate note, I head another idea. The requests for images are issued by user browsers so it doesn't seem like they banned us specifically, unless they checked for a referrer or sth... I suppose they are blocking several quick requests from same ip. We could download the images asynchronously, say every 5 secs. The user doesn't need see them all at instance after all.
This still leaves the problem of possibly violating private API.
Another idea would be to write a simple web scraper and make it work in the background.

**Comment by siaw23-retired** [comment]
how about using S3 or preloading the images with JS?

**Comment by paneq** [comment]
How about just saving SVG version in DB? It's very small.

```
Content-Type: image/svg+xml
Content-Length: 11993
```

**Comment by andrzejkrzywda** [comment]
Let's move the discussion to a new issue which is about persisting the snapcodes somehow.

**Comment by andrzejkrzywda** [comment]
@rusilko just to be sure - this PR is ready to be merged now?

**Comment by rusilko** [comment]
@andrzejkrzywda yes :) I just need to resolve conflicts.

**Pull request merged**
